### ISSUE TITLE
Remove useless mods

### ISSUE THREAD

**Issue by EvanHsieh0415** [Mango-Minecraft-Project/Creative-Drawers-Producer#4]
# Confirm

<details>
    <summary> Confirms </summary>

- [x] Vanilla Hammers
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/4682c107-a05b-4e28-a3d1-711ee62ff3fe)
- [x] Vanilla Excavators
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/cbd85da8-5877-41b1-b7c8-7fd331778a5e)
- [x] Redstone Pen
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/7307a003-834d-4942-9d2b-90f1a5866a6b)
- [x] The Undergarden
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/b68d82ea-871a-4860-8f12-639934299070)
- [x] Hexerei
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/d7467688-24bd-4d44-8505-45c0dd829729)
- [x] Gauges and Switches
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/8973e9b0-4e87-4480-a96c-7b22e552b11f)
- [x] Chisels & bits
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/910c0bd5-1a65-45ba-97ec-cbe71f1adab9)
- [x] Some Assembly Required
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/36efc471-86ea-4705-aeb1-e784b1850984)
- [x] Decorative Blocks
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/820459ab-df63-433a-9154-b9ab362ceb8d)
- [x] Comforts
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/fc9eecad-7114-4f86-bd46-45af1a606f67)
- [x] AIOT Botania
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/5c01dcfe-7dbb-4849-af5a-b81f836a1689)
- [x] Super Circuit Maker
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/416c973d-e8cf-46f1-95cb-0d5fd1b7e240)
- [x] Tetra
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/54780c50-2fc5-4272-b3f1-4e5945b1b190)
- [x] Sushi Go Crafting
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/e06f5d9b-a59e-449b-96cd-23e042a65601)
- [x] Connected Glass
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/23423a39-770f-45b3-9edc-0a1027099126)
- [x] Little Logistics
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/cf843b5b-7bed-4541-820f-319a67d32eca)
- [x] More Minecarts
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/9c90115f-fb81-46be-ab74-7107d1d8f605)
- [x] Little Contraptions
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/978ee2b0-a7f9-40e4-8ec0-93d32a08a679)
- [x] Save Your Pets
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/47962f8d-dfc0-4725-baef-a4877c5e2f39)
- [x] 'Dustrial Decor
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/7322accb-a299-45a2-8bdf-8b7db49eb6a2)
- [x] Crash Utilities | 崩潰實用工具
- [x] Charm of Undying | 不死圖騰可裝備到飾品
- [x] Diagonal Fences | 斜向連接的柵欄
- [x] Dynamic View | 動態視野遠近
- [x] Emojiful | 顯示更多表情符號
- [x] Enchantment Descriptions | 附魔描述
- [x] Friendly Fire | 防止打到寵物
- [x] Guard Villagers | 村民守衛
- [x] Login Protection | 登入保護
- [x] Mod Name Tooltip | 模組名稱提示（已包含在JEI中）
- [x] More Dragon Eggs | 更多龍蛋
- [x] Notes | 筆記
- [x] Oculus | 光影
- [x] Open Loader | 開放載入器（未使用）
- [x] Plonk | 可隨處放置的物品
- [x] ServerConfig Updater | 伺服器設置更新器
- [x] Shield Parry | 全方位盾牌
- [x] Simple Discord Rich Presence | 簡易Discord遊玩中提示
- [x] Stack Refill | 自動補充物品（已包含在Inventory Profiles Next中）
- [x] Toast Control | 提示控制（已包含在中Rubidium / Embeddium中）
- [x] Rain Shield | 雨盾
- [x] Collective | 前置

</details>

# To check

<details>
    <summary> To check</summary>

</details>

# Cancel

<details>
    <summary> Cancel to Delete </summary>

- <del>Structure Items (debug用的?)</del> *// 模組前置*
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/8d6ed970-5ad6-4084-bb91-67a1e77a07cf)
- <del>Mining Gadgets</del> *// 任務所需*
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/b5f01908-272d-46fb-8fd0-717ac34c2761)
- <del>Spirit</del> *// 主線相關*
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/3c43e34f-e44b-43bf-b02a-4c04196a549a)
- <del>Chipped</del> *// 常用裝飾模組*
  ![圖片](https://github.com/Mango-Minecraft-Project/Creative-Drawers-Producer/assets/74277414/bd81bb45-edf9-4b0d-af84-24dc79b5306f)

</details>

**Comment by meishiffx** [comment]
Spirit与主线有联系的，不改动配方情况下不能删除
Chipped是一个非常好的装饰mod不建议删除
其余基本使用频率不高可以考虑删除

**Comment by EvanHsieh0415** [comment]
done

**Comment by EvanHsieh0415** [comment]
- [ ] Emojiful
